[workspace]
members = [ "base", "term", "wasm" ]
resolver = "2"

[profile.release]
incremental = true

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
