[package]
name = "wrl-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wrl-base = { path = "../base" }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.95"
